services:
  - type: web
    name: locify-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 100 --timeout 120 --bind 0.0.0.0:10000 server:app
    envVars:
      - key: BACKEND_PORT
        value: 10000
      - key: ADMIN_COOKIE_PASS
        generateValue: true
      - key: MONGO_URL
        value: test
